# Conda Environment Setup Instructions
#  - Using an environment.yml file with conda
#  - Key Terminal Commands:
#
#    install:
#    conda deactivate (preparation for installation)
#    conda env create -f environment.yml
#    conda env update --file environment.yml --prune
#
#    export:
#    conda env export --name salary > environment.yml
#    conda env remove --name salary
#    conda env list

name: salary
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio==4.2.0
  - appdirs==1.4.4
  - appnope
  - asgiref==3.7.2
  - asttokens
  - attrs==23.2.0
  - cachetools==5.3.3
  - certifi==2024.2.2
  - charset-normalizer==3.3.2
  - click==8.1.7
  - cloudpickle==3.0.0
  - comm
  - contourpy==1.2.0
  - cycler==0.12.1
  - debugpy
  - decorator
  - exceptiongroup
  - executing
  - fonttools==4.49.0
  - google-api-core==2.17.1
  - google-api-python-client==2.121.0
  - google-auth==2.28.2
  - google-auth-httplib2==0.2.0
  - google-auth-oauthlib==1.2.0
  - googleapis-common-protos==1.62.0
  - h11==0.14.0
  - htmltools==0.5.1
  - httplib2==0.22.0
  - idna==3.6
  - importlib-metadata
  - ipykernel
  - ipython
  - ipywidgets==8.1.2
  - jedi
  - joblib==1.3.2
  - jsonschema==4.21.1
  - jsonschema-specifications==2023.12.1
  - jupyter_client
  - jupyter_core
  - jupyterlab_widgets==3.0.10
  - kiwisolver==1.4.5
  - lightgbm==4.3.0
  - linkify-it-py==2.0.3
  - llvmlite==0.42.0
  - markdown-it-py==3.0.0
  - matplotlib==3.8.3
  - matplotlib-inline
  - mdit-py-plugins==0.4.0
  - mdurl==0.1.2
  - nbformat==5.9.2
  - numba==0.59.0
  - numpy
  - oauthlib==3.2.2
  - packaging
  - pandas==2.2.0
  - parso
  - patsy==0.5.6
  - pexpect
  - pickleshare
  - pillow==10.2.0
  - platformdirs
  - plotly==5.19.0
  - prompt-toolkit==3.0.36
  - protobuf==4.25.3
  - psutil
  - ptyprocess
  - pyasn1==0.5.1
  - pyasn1-modules==0.3.0
  - Pygments
  - PyJWT==2.8.0
  - pyparsing==3.1.1
  - python-dateutil
  - python-multipart==0.0.9
  - pytz==2024.1
  - pyzmq
  - questionary==2.0.1
  - referencing==0.33.0
  - requests==2.31.0
  - requests-oauthlib==1.3.1
  - rpds-py==0.18.0
  - rsa==4.9
  - scikit-learn==1.4.1.post1
  - scipy
  - semver==2.13.0
  - shap==0.44.1
  - shiny==0.7.1
  - six
  - slicer==0.0.7
  - sniffio==1.3.0
  - starlette==0.34.0
  - statsmodels==0.14.1
  - StrEnum==0.4.15
  - tenacity==8.2.3
  - threadpoolctl==3.3.0
  - tornado
  - tqdm==4.66.2
  - traitlets
  - typing_extensions
  - uritemplate==4.1.1
  - urllib3==2.2.1
  - uvicorn==0.27.1
  - watchfiles==0.21.0
  - wcwidth
  - websockets==12.0
  - widgetsnbextension==4.0.10
  - xgboost==2.0.3
  - zipp
  - pip
  - pip:
    - tzdata==2024.1
    - shinywidgets==0.3.0
    - shinyswatch==0.4.2
    - rsconnect-python==1.22.0
    - gspread==6.0.2
    - fastjsonschema==2.19.1
    - faicons==0.2.2
    - stack-data
    - pure-eval
    - nest-asyncio
